---
title : "DBSCAN"
output : html_document
author : "Fakhri Ilham (18523060)"
author : "Muhammad Farhan (18523099)"
---

## Pada DBSCAN 

## Importing the libraries
## STEP 1:
```{r}
library(readxl)
library(factoextra)
mall_customers <- read_excel("Mall_Customers.xlsx")
data("mall_customers")
df <- mall_customers[, 3:2]
```

## Ploting data
## STEP 2:
```{r}
plot(df, pch=16)

```

## STEP 3:
## Kita melakukan clustering, bahwa kita akan melakukan 
```{r}
set.seed(123)
km.res <- kmeans(df, 5, nstart = 25)
fviz_cluster(km.res, df, frame = FALSE, geom = "point")

```

## STEP 4:
## ss
```{r}
install.packages("fpc")
library("fpc")
set.seed(123)
db <- dbscan(df, eps = 0.15, MinPts = 5)
plot(db, df, main = "DBSCAN", frame = FALSE)
print(db)
```


## STEP 4:
## ss
```{r}
library("factoextra")
fviz_cluster(db, df, stand = FALSE, frame = FALSE, geom = "point")
```

## STEP 5
```{r}
print(db)
```


## STEP 6
```{r}
db$cluster
```

## STEP 7   
```{r}
library(dbscan)
```

## STEP 8
```{r}
kNNdistplot(df, k =  5)
abline(h = 0.15, lty = 2)
```
